// This file is auto-generated by @hey-api/openapi-ts

export type Body_authentication_login = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type Page_UserPublic_ = {
  items: Array<UserPublic>
  after: string | null
  before: string | null
}

export type ResetPassword = {
  token: string
  password: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UserCreate = {
  email: string
  name: string
  password: string
}

export type UserPublic = {
  email: string
  id: string
  name: string
}

export type UserUpdate = {
  email?: string | null
  name?: string | null
  password?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AuthenticationLoginData = {
  formData: Body_authentication_login
}

export type AuthenticationLoginResponse = Token

export type AuthenticationRecoverPasswordData = {
  email: string
}

export type AuthenticationRecoverPasswordResponse = Message

export type AuthenticationResetPasswordData = {
  requestBody: ResetPassword
}

export type AuthenticationResetPasswordResponse = Message

export type HealthResponse = boolean

export type UsersGetUsersData = {
  count: number
  cursor: string | null
}

export type UsersGetUsersResponse = Page_UserPublic_

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersGetMeResponse = UserPublic

export type UsersGetUserData = {
  userId: string
}

export type UsersGetUserResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = unknown
